# Generated by Django 3.2.9 on 2021-12-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name': 'Recipe Category', 'verbose_name_plural': 'Recipe Categories'},
        ),
    ]
